In [2]:
import torch

In [5]:
t = torch.FloatTensor([[1,2,3],
                      [4,5,6],
                      [7,8,9],
                      [10,11,12]])

In [7]:
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [13]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([1., 2., 3.])


In [16]:
# Same Shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [18]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])      # 3 -> [[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [23]:
print('-'*13)
print('Mul vs Matmul')
print('-'*13)
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ', m1.shape)

-------------
Mul vs Matmul
-------------
