In [187]:
import random
import torch
import torch.nn as nn
from torch import optim


import pandas as pd
import warnings
warnings.filterwarnings('ignore')
lines = pd.read_csv('C:/Users/JeongMyeong/Desktop/2020/연구실/잡다한것/dataset/fra.txt', names=['src', 'tar','drop'], sep='\t')
lines.drop(['drop'], inplace=True, axis=1)
len(lines)


170651

In [188]:
lines = lines.iloc[[10000,20000,30000,40000,50000],:]

In [189]:
lines

src                                   tar
10000         Do you have one?                         En as-tu un ?
20000       Please forgive me.                Veuillez me pardonner.
30000     Make another choice.                  Fais un autre choix.
40000   I agree with everyone.  Je suis d'accord avec tout le monde.
50000  We could use your help.     Nous pourrions utiliser ton aide.

In [190]:
raw = [str(a)+"\t" + str(b) for a,b in zip(lines['src'], lines['tar'])]

In [191]:
raw

['Do you have one?\tEn as-tu un\u202f?',
 'Please forgive me.\tVeuillez me pardonner.',
 'Make another choice.\tFais un autre choix.',
 "I agree with everyone.\tJe suis d'accord avec tout le monde.",
 'We could use your help.\tNous pourrions utiliser ton aide.']

In [174]:
torch.manual_seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [249]:
raw = ["I feel hungry.	나는 배가 고프다.",
       "Pytorch is very easy.	파이토치는 매우 쉽다.",
       "Pytorch is a framework for deep learning.	파이토치는 딥러닝을 위한 프레임워크이다.",
       "Pytorch is very clear to use.	파이토치는 사용하기 매우 직관적이다."]

In [250]:
SOS_token = 0
EOS_token = 1

In [251]:
class Vocab:
    def __init__(self):
        self.vocab2index = {"<SOS>": SOS_token, "<EOS>": EOS_token}       # dictionary
        self.index2vocab = {SOS_token : "<SOS>", EOS_token: "<EOS>"}      # dictionary
        self.vocab_count = {}                                             # dictionary 단어 count
        self.n_vocab = len(self.vocab2index)                              # vocab의 index값 (temp)
        
    def add_vocab(self, sentence):
        for word in sentence.split(" "):
            if word not in self.vocab2index:                              # 만약 vocab2index dictionary에 단어가 없으면
                self.vocab2index[word] = self.n_vocab                     # vocab2index dictionary에 추가하면서 index를 표기해준다.
                self.vocab_count[word] = 1                                # 추가한 단어의 갯수 여기서는 처음 들어가는 거라 1로 고정
                self.index2vocab[self.n_vocab] = word                     # vocab2index에서 index 값에 맞게 word를 넣어준다.
                self.n_vocab += 1                                         # 인덱스 1올려준다.
            else:
                self.vocab_count[word] += 1                               # 만약 있는 단어면 근야 count만 올려준다.

def filter_pair(pair, source_max_length, target_max_length):              # pair에는 데이터 한줄씩 들어간다. [영어, 한글] pair[0]는 영어 pair[1]은 한글
    return len(pair[0].split(" ")) < source_max_length and len(pair[1].split(" ")) < target_max_length

def preprocess(corpus, source_max_length, target_max_length):
    print('reading corpus...') 
    pairs = []
    for line in corpus:
        pairs.append([s for s in line.strip().lower().split('\t')])
    print('Read {} sentence pairs', format(len(pairs)))
    print(pairs)
    pairs = [pair for pair in pairs if filter_pair(pair, source_max_length, target_max_length)]
    print('Trimmed to {} sentence pairs'.format(len(pairs)))
    
    source_vocab = Vocab()
    target_vocab = Vocab()
    
    print('Counting words...')
    for pair in pairs:
        source_vocab.add_vocab(pair[0])                                   # 영어와 한글을 각각 add_vocab 해준다.
        target_vocab.add_vocab(pair[1])
    print('source vocab size = ', source_vocab.n_vocab)
    print('target vocab size = ', target_vocab.n_vocab)
    
    return pairs, source_vocab, target_vocab

In [258]:
SOURCE_MAX_LENGTH = 10
TARGET_MAX_LENGTH = 12
load_pairs, load_source_vocab, load_target_vocab = preprocess(raw, SOURCE_MAX_LENGTH, TARGET_MAX_LENGTH)


reading corpus...
Read {} sentence pairs 4
[['i feel hungry.', '나는 배가 고프다.'], ['pytorch is very easy.', '파이토치는 매우 쉽다.'], ['pytorch is a framework for deep learning.', '파이토치는 딥러닝을 위한 프레임워크이다.'], ['pytorch is very clear to use.', '파이토치는 사용하기 매우 직관적이다.']]
Trimmed to 4 sentence pairs
Counting words...
source vocab size =  17
target vocab size =  13


In [259]:
load_target_vocab.index2vocab

{0: '<SOS>',
 1: '<EOS>',
 2: '나는',
 3: '배가',
 4: '고프다.',
 5: '파이토치는',
 6: '매우',
 7: '쉽다.',
 8: '딥러닝을',
 9: '위한',
 10: '프레임워크이다.',
 11: '사용하기',
 12: '직관적이다.'}

In [260]:
class Encoder(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(Encoder, self).__init__()
        self.hidden_size = hidden_size
        self.embedding = nn.Embedding(input_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size)
        
    def forward(self, x, hidden):
        x = self.embedding(x).view(1, 1, -1)
        x, hidden = self.gru(x, hidden)
        return x, hidden

In [261]:
class Decoder(nn.Module):
    def __init__(self, hidden_size, output_size):
        super(Decoder, self).__init__()
        self.hidden_size = hidden_size
        self.embedding = nn.Embedding(output_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size)
        self.out = nn.Linear(hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim=1)
        
    def forward(self, x, hidden):
        x = self.embedding(x).view(1, 1, -1)
        x, hidden = self.gru(x, hidden)
        x = self.softmax(self.out(x[0]))
        return x, hidden

In [262]:
def tensorize(vocab, sentence):
    indexs = [vocab.vocab2index[word] for word in sentence.split(" ")]
    indexs.append(vocab.vocab2index["<EOS>"])
    return torch.Tensor(indexs).long().to(device).view(-1,1)

In [218]:
%%time
enc_hidden_size = 16
dec_hidden_size = enc_hidden_size

enc = Encoder(load_source_vocab.n_vocab, enc_hidden_size).to(device)
dec = Decoder(dec_hidden_size, load_target_vocab.n_vocab).to(device)

train(load_pairs, load_source_vocab, load_target_vocab, enc, dec, 10, print_every=1000)

tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([[0]], device='cuda:0')
Wall time: 43.5 ms


In [ ]:
train(load_pairs, load_source_vocab, load_target_vocab, enc, dec, 2000, print_every=100)

In [263]:
def train(pairs, source_vocab, target_vocab, encoder, decoder, n_iter, print_every=1000, learning_rate=0.01):
    # n_iter = batch_size
    loss_total = 0
    encoder_optimizer = optim.SGD(encoder.parameters(), lr=learning_rate)
    decoder_optimizer = optim.SGD(decoder.parameters(), lr=learning_rate)
    
    training_batch = [random.choice(pairs) for _ in range(n_iter)]
    training_source = [tensorize(source_vocab, pair[0]) for pair in training_batch]
    training_target = [tensorize(target_vocab, pair[1]) for pair in training_batch]
    
    criterion = nn.NLLLoss()
    for i in range(1, n_iter + 1):
        source_tensor = training_source[i - 1]
        target_tensor = training_target[i - 1]
        
        encoder_hidden = torch.zeros([1, 1, encoder.hidden_size]).to(device)
        
        encoder_optimizer.zero_grad()
        decoder_optimizer.zero_grad()
        
        source_length = source_tensor.size(0)
        target_length = target_tensor.size(0)
        
        loss = 0
        
        for enc_input in range(source_length):
            _, encoder_hidden = encoder(source_tensor[enc_input], encoder_hidden)
            
        decoder_input = torch.Tensor([[SOS_token]]).long().to(device)
        decoder_hidden = encoder_hidden
        
        for di in range(target_length):
            decoder_output, decoder_hidden = decoder(decoder_input, decoder_hidden)
            loss += criterion(decoder_output, target_tensor[di])
            decoder_input = target_tensor[di]
        
        
        loss.backward()
        
        encoder_optimizer.step()
        decoder_optimizer.step()
        
        loss_iter = loss.item() / target_length
        loss_total += loss_iter
        
        if i % print_every == 0:
            loss_avg = loss_total / print_every
            loss_total = 0
            print("[{} - {}%] loss = {:05.4f}".format(i, i/n_iter * 100, loss_avg))

In [264]:
def evaluate(pairs, source_vocab, target_vocab, encoder, decoder, target_max_length):
    for pair in pairs:
        print(">", pair[0])
        print("=", pair[1])
        source_tensor = tensorize(source_vocab, pair[0])
        source_length = source_tensor.size()[0]
        encoder_hidden = torch.zeros([1, 1, encoder.hidden_size]).to(device)
        
        for ei in range(source_length):
            _, encoder_hidden = encoder(source_tensor[ei], encoder_hidden)
            
        decoder_input = torch.Tensor([[SOS_token]]).long().to(device)
        decoder_hidden = encoder_hidden.to(device)
        decoded_words = []
        
        for di in range(target_max_length):
            decoder_output, decoder_hidden = decoder(decoder_input, decoder_hidden)
            _, top_index = decoder_output.data.topk(1)
#             print('item : ',decoder_output.data.topk(1)[1])
            if top_index.item() == EOS_token:
                decoded_words.append("<EOS>")
                break
            else:
                decoded_words.append(target_vocab.index2vocab[top_index.item()])
            
            decoder_input = top_index.squeeze().detach()
            
        predict_words = decoded_words
        predict_sentence = " ".join(predict_words)
        print("<", predict_sentence)
        print("")          

In [277]:
%%time
enc_hidden_size = 16
dec_hidden_size = enc_hidden_size
enc = Encoder(load_source_vocab.n_vocab, enc_hidden_size).to(device)
dec = Decoder(dec_hidden_size, load_target_vocab.n_vocab).to(device)

Wall time: 6.52 ms


In [274]:
enc

Encoder(
  (embedding): Embedding(17, 16)
  (gru): GRU(16, 16)
)

In [1]:
%%time
import random
encoder = Encoder().to(device)
decoder = Decoder().to(device)
learning_rate=0.01
n_iter = 2000
loss_list = []

loss_total = 0
encoder_optimizer = optim.SGD(encoder.parameters(), lr=learning_rate)
decoder_optimizer = optim.SGD(decoder.parameters(), lr=learning_rate)

training_batch = [random.choice(load_pairs) for _ in range(n_iter)]
training_source = [tensorize(load_source_vocab, pair[0]) for pair in training_batch]
training_target = [tensorize(load_target_vocab, pair[1]) for pair in training_batch]


criterion = nn.NLLLoss()
for i in range(1, n_iter + 1):
    source_tensor = training_source[i - 1]
    target_tensor = training_target[i - 1]
    
    encoder_hidden = torch.zeros([1, 1, encoder.hidden_size]).to(device)    
    
    encoder_optimizer.zero_grad()
    decoder_optimizer.zero_grad()
    
    source_length = source_tensor.size(0)
    target_length = target_tensor.size(0)
    
    loss = 0

    for enc_input in range(source_length):
        _, encoder_hidden = encoder(source_tensor[enc_input], encoder_hidden)
#     # 한 문장의 encoder 끝
        
    decoder_input = torch.Tensor([[SOS_token]]).long().to(device)
    decoder_hidden = encoder_hidden
    
    for di in range(target_length):
        decoder_output, decoder_hidden = decoder(decoder_input, decoder_hidden)
        loss += criterion(decoder_output, target_tensor[di])
        decoder_input = target_tensor[di]
        
    loss.backward()
    encoder_optimizer.step()
    decoder_optimizer.step()

    loss_iter = loss.item() / target_length
    loss_total += loss_iter
    
    if i % 100 == 0:
        loss_avg = loss_total / 100
        loss_total = 0
        print("[{} - {}%] loss = {:05.4f}".format(i, i/n_iter * 100, loss_avg))

NameError: name 'Encoder' is not defined

In [278]:
train(load_pairs, load_source_vocab, load_target_vocab, enc, dec, 2000, print_every=100)

[100 - 5.0%] loss = 2.1740
[200 - 10.0%] loss = 1.5694
[300 - 15.0%] loss = 1.1082
[400 - 20.0%] loss = 0.7854
[500 - 25.0%] loss = 0.6191
[600 - 30.0%] loss = 0.5136
[700 - 35.0%] loss = 0.4195
[800 - 40.0%] loss = 0.3481
[900 - 45.0%] loss = 0.3044
[1000 - 50.0%] loss = 0.2569
[1100 - 55.00000000000001%] loss = 0.2386
[1200 - 60.0%] loss = 0.2106
[1300 - 65.0%] loss = 0.1916
[1400 - 70.0%] loss = 0.1659
[1500 - 75.0%] loss = 0.1511
[1600 - 80.0%] loss = 0.1276
[1700 - 85.0%] loss = 0.1184
[1800 - 90.0%] loss = 0.1007
[1900 - 95.0%] loss = 0.0891
[2000 - 100.0%] loss = 0.0751


In [35]:
evaluate(load_pairs, load_source_vocab, load_target_vocab, enc, dec, TARGET_MAX_LENGTH)

> do you have one?
= en as-tu un ?
< en as-tu un ? <EOS>

> please forgive me.
= veuillez me pardonner.
< veuillez me pardonner. <EOS>

> make another choice.
= fais un autre choix.
< fais un autre choix. <EOS>

> i agree with everyone.
= je suis d'accord avec tout le monde.
< je suis d'accord avec tout le monde. <EOS>

